from datetime import date

DEMO_TALENTS = [
    {
        "nom": "Dupuis",
        "prenom": "Anna",
        "date_naissance": date(1992, 4, 15),
        "description": "Comédienne, voix-off, chanteuse. Expérience au théâtre et au cinéma.",
        "taille": "170",
        "poids": "58",
        "permis": "B",
        "localisations": ["Paris"],
        "langues": [("Français", "bilingue"), ("Anglais", "courant")],
        "competences": [("Chant", "professionnel", "chant"), ("Danse", "débutant", "danse")],
        "attributs": [("Couleur des yeux", "Verts"), ("Couleur des cheveux", "Châtain clair")],
        "contacts": [("email", "anna.dupuis@mail.com", "Pro"), ("instagram", "@anna.dupuis", "")],
        "experiences": [
            {"annee": "2022", "titre": "Le Grand Théâtre", "description": "Rôle principal", "role": "Actrice", "type_experience": "théâtre"},
            {"annee": "2023", "titre": "Pub L'Oréal", "description": "Spot TV", "role": "Mannequin", "type_experience": "publicité"},
        ],
    },
    {
        "nom": "Martin",
        "prenom": "Lucas",
        "date_naissance": date(1988, 9, 23),
        "description": "Acteur, cascadeur, expérience en séries TV.",
        "taille": "180",
        "poids": "75",
        "permis": "B",
        "localisations": ["Lyon"],
        "langues": [("Français", "natif"), ("Espagnol", "notions")],
        "competences": [("Cascade", "professionnel", "sport"), ("Sport", "avancé", "sport")],
        "attributs": [("Tattoos", "Oui"), ("Barbe", "Oui")],
        "contacts": [("email", "lucas.martin@mail.com", "Pro"), ("linkedin", "linkedin.com/in/lucasmartin", "")],
        "experiences": [
            {"annee": "2021", "titre": "Série 'Police Urbaine'", "description": "Cascadeur principal", "role": "Cascadeur", "type_experience": "série TV"},
        ],
    },
    {
        "nom": "Leroy",
        "prenom": "Sophie",
        "date_naissance": date(1995, 7, 10),
        "description": "Chanteuse pop et comédie musicale, danseuse.",
        "taille": "165",
        "poids": "54",
        "permis": "",
        "localisations": ["Marseille"],
        "langues": [("Français", "bilingue"), ("Italien", "courant")],
        "competences": [("Chant", "professionnel", "chant"), ("Danse", "avancé", "danse")],
        "attributs": [("Cheveux", "Noirs"), ("Yeux", "Marron")],
        "contacts": [("email", "sophie.leroy@mail.com", "Pro"), ("facebook", "fb.com/sophieleroy", "")],
        "experiences": [
            {"annee": "2020", "titre": "Comédie musicale 'Rêves'", "description": "Chanteuse principale", "role": "Chanteuse", "type_experience": "théâtre"},
        ],
    },
    {
        "nom": "Nguyen",
        "prenom": "Théo",
        "date_naissance": date(1990, 2, 5),
        "description": "Danseur hip-hop, chorégraphe, acteur pub.",
        "taille": "175",
        "poids": "68",
        "permis": "A",
        "localisations": ["Toulouse"],
        "langues": [("Français", "bilingue"), ("Anglais", "notions")],
        "competences": [("Danse", "professionnel", "danse"), ("Chorégraphie", "avancé", "danse")],
        "attributs": [("Cheveux", "Bruns"), ("Yeux", "Noisette")],
        "contacts": [("email", "theo.nguyen@mail.com", "Pro"), ("instagram", "@theo.dance", "")],
        "experiences": [
            {"annee": "2019", "titre": "Pub Nike", "description": "Danseur principal", "role": "Danseur", "type_experience": "publicité"},
        ],
    },
    {
        "nom": "Morel",
        "prenom": "Camille",
        "date_naissance": date(1997, 11, 2),
        "description": "Mannequin, actrice, influenceuse.",
        "taille": "172",
        "poids": "56",
        "permis": "B",
        "localisations": ["Bordeaux"],
        "langues": [("Français", "bilingue"), ("Anglais", "courant")],
        "competences": [("Mannequinat", "professionnel", "mode"), ("Photo", "avancé", "mode")],
        "attributs": [("Cheveux", "Blonds"), ("Yeux", "Bleus")],
        "contacts": [("email", "camille.morel@mail.com", "Pro"), ("instagram", "@camillemode", "")],
        "experiences": [
            {"annee": "2021", "titre": "Défilé Chanel", "description": "Mannequin", "role": "Mannequin", "type_experience": "mode"},
        ],
    },
    {
        "nom": "Petit",
        "prenom": "Julien",
        "date_naissance": date(1985, 6, 18),
        "description": "Humoriste, comédien, animateur radio.",
        "taille": "178",
        "poids": "72",
        "permis": "B",
        "localisations": ["Paris"],
        "langues": [("Français", "natif"), ("Anglais", "courant")],
        "competences": [("Humour", "professionnel", "scène"), ("Animation", "avancé", "scène")],
        "attributs": [("Cheveux", "Châtain"), ("Yeux", "Verts")],
        "contacts": [("email", "julien.petit@mail.com", "Pro"), ("twitter", "@julienhumour", "")],
        "experiences": [
            {"annee": "2022", "titre": "Festival du Rire", "description": "One-man show", "role": "Humoriste", "type_experience": "scène"},
        ],
    },
    {
        "nom": "Roux",
        "prenom": "Claire",
        "date_naissance": date(1994, 3, 30),
        "description": "Actrice, voix-off, théâtre classique.",
        "taille": "168",
        "poids": "57",
        "permis": "",
        "localisations": ["Lille"],
        "langues": [("Français", "bilingue"), ("Allemand", "notions")],
        "competences": [("Théâtre", "professionnel", "théâtre"), ("Voix-off", "avancé", "voix")],
        "attributs": [("Cheveux", "Roux"), ("Yeux", "Verts")],
        "contacts": [("email", "claire.roux@mail.com", "Pro"), ("instagram", "@clairetheatre", "")],
        "experiences": [
            {"annee": "2021", "titre": "Cyrano de Bergerac", "description": "Roxane", "role": "Actrice", "type_experience": "théâtre"},
        ],
    },
    {
        "nom": "Dubois",
        "prenom": "Maxime",
        "date_naissance": date(1991, 8, 12),
        "description": "Musicien, guitariste, compositeur.",
        "taille": "182",
        "poids": "80",
        "permis": "B",
        "localisations": ["Nantes"],
        "langues": [("Français", "natif"), ("Anglais", "courant")],
        "competences": [("Guitare", "professionnel", "musique"), ("Composition", "avancé", "musique")],
        "attributs": [("Cheveux", "Bruns"), ("Yeux", "Bleus")],
        "contacts": [("email", "maxime.dubois@mail.com", "Pro"), ("facebook", "fb.com/maxguitar", "")],
        "experiences": [
            {"annee": "2020", "titre": "Album 'Blue Sky'", "description": "Compositeur, guitariste", "role": "Musicien", "type_experience": "musique"},
        ],
    },
    {
        "nom": "Girard",
        "prenom": "Elise",
        "date_naissance": date(1993, 12, 5),
        "description": "Danseuse contemporaine, chorégraphe.",
        "taille": "167",
        "poids": "53",
        "permis": "",
        "localisations": ["Montpellier"],
        "langues": [("Français", "bilingue"), ("Espagnol", "courant")],
        "competences": [("Danse", "professionnel", "danse"), ("Chorégraphie", "avancé", "danse")],
        "attributs": [("Cheveux", "Bruns"), ("Yeux", "Verts")],
        "contacts": [("email", "elise.girard@mail.com", "Pro"), ("instagram", "@elisedanse", "")],
        "experiences": [
            {"annee": "2022", "titre": "Festival Danse Sud", "description": "Solo contemporain", "role": "Danseuse", "type_experience": "danse"},
        ],
    },
    {
        "nom": "Bernard",
        "prenom": "Hugo",
        "date_naissance": date(1987, 5, 27),
        "description": "Acteur, voix-off, animateur TV.",
        "taille": "183",
        "poids": "77",
        "permis": "B",
        "localisations": ["Strasbourg"],
        "langues": [("Français", "natif"), ("Allemand", "courant")],
        "competences": [("Animation", "professionnel", "tv"), ("Voix-off", "avancé", "voix")],
        "attributs": [("Cheveux", "Châtain"), ("Yeux", "Marron")],
        "contacts": [("email", "hugo.bernard@mail.com", "Pro"), ("linkedin", "linkedin.com/in/hugobernard", "")],
        "experiences": [
            {"annee": "2023", "titre": "Emission 'Top Chrono'", "description": "Présentateur", "role": "Animateur", "type_experience": "tv"},
        ],
    },
    {
        "nom": "Fournier",
        "prenom": "Léa",
        "date_naissance": date(1998, 1, 15),
        "description": "Chanteuse lyrique, pianiste.",
        "taille": "163",
        "poids": "50",
        "permis": "",
        "localisations": ["Paris"],
        "langues": [("Français", "natif"), ("Italien", "courant")],
        "competences": [("Chant lyrique", "professionnel", "chant"), ("Piano", "avancé", "musique")],
        "attributs": [("Cheveux", "Noirs"), ("Yeux", "Noisette")],
        "contacts": [("email", "lea.fournier@mail.com", "Pro"), ("instagram", "@lealyrique", "")],
        "experiences": [
            {"annee": "2022", "titre": "Opéra Garnier", "description": "Soprano", "role": "Chanteuse", "type_experience": "musique"},
        ],
    },
    {
        "nom": "Blanc",
        "prenom": "Antoine",
        "date_naissance": date(1989, 4, 9),
        "description": "Acteur, réalisateur court-métrage.",
        "taille": "177",
        "poids": "73",
        "permis": "B",
        "localisations": ["Nice"],
        "langues": [("Français", "bilingue"), ("Anglais", "courant")],
        "competences": [("Jeu", "professionnel", "cinéma"), ("Réalisation", "avancé", "cinéma")],
        "attributs": [("Cheveux", "Châtain clair"), ("Yeux", "Bleus")],
        "contacts": [("email", "antoine.blanc@mail.com", "Pro"), ("twitter", "@antoineblanc", "")],
        "experiences": [
            {"annee": "2021", "titre": "Court-métrage 'Évasion'", "description": "Acteur, réalisateur", "role": "Acteur/Réalisateur", "type_experience": "cinéma"},
        ],
    },
    {
        "nom": "Garnier",
        "prenom": "Sarah",
        "date_naissance": date(1996, 6, 21),
        "description": "Mannequin, actrice, influenceuse.",
        "taille": "174",
        "poids": "57",
        "permis": "B",
        "localisations": ["Paris"],
        "langues": [("Français", "bilingue"), ("Anglais", "courant")],
        "competences": [("Mannequinat", "professionnel", "mode"), ("Photo", "avancé", "mode")],
        "attributs": [("Cheveux", "Blonds"), ("Yeux", "Verts")],
        "contacts": [("email", "sarah.garnier@mail.com", "Pro"), ("instagram", "@sarahmode", "")],
        "experiences": [
            {"annee": "2022", "titre": "Défilé Dior", "description": "Mannequin", "role": "Mannequin", "type_experience": "mode"},
        ],
    },
    {
        "nom": "Lemoine",
        "prenom": "Paul",
        "date_naissance": date(1993, 2, 17),
        "description": "Musicien, batteur, compositeur.",
        "taille": "179",
        "poids": "76",
        "permis": "B",
        "localisations": ["Rennes"],
        "langues": [("Français", "natif"), ("Anglais", "courant")],
        "competences": [("Batterie", "professionnel", "musique"), ("Composition", "avancé", "musique")],
        "attributs": [("Cheveux", "Bruns"), ("Yeux", "Noisette")],
        "contacts": [("email", "paul.lemoine@mail.com", "Pro"), ("facebook", "fb.com/paulbatteur", "")],
        "experiences": [
            {"annee": "2020", "titre": "Groupe 'Rythmix'", "description": "Batteur, compositeur", "role": "Musicien", "type_experience": "musique"},
        ],
    },
    {
        "nom": "Marchand",
        "prenom": "Julie",
        "date_naissance": date(1995, 5, 29),
        "description": "Danseuse classique, professeur de danse.",
        "taille": "166",
        "poids": "52",
        "permis": "",
        "localisations": ["Lyon"],
        "langues": [("Français", "bilingue"), ("Russe", "notions")],
        "competences": [("Danse classique", "professionnel", "danse"), ("Enseignement", "avancé", "danse")],
        "attributs": [("Cheveux", "Blonds"), ("Yeux", "Bleus")],
        "contacts": [("email", "julie.marchand@mail.com", "Pro"), ("instagram", "@juliedanse", "")],
        "experiences": [
            {"annee": "2021", "titre": "Opéra de Lyon", "description": "Danseuse étoile", "role": "Danseuse", "type_experience": "danse"},
        ],
    },
    {
        "nom": "Robin",
        "prenom": "Alexandre",
        "date_naissance": date(1990, 10, 13),
        "description": "Acteur, metteur en scène.",
        "taille": "181",
        "poids": "79",
        "permis": "B",
        "localisations": ["Paris"],
        "langues": [("Français", "bilingue"), ("Anglais", "courant")],
        "competences": [("Théâtre", "professionnel", "théâtre"), ("Mise en scène", "avancé", "théâtre")],
        "attributs": [("Cheveux", "Bruns"), ("Yeux", "Marron")],
        "contacts": [("email", "alexandre.robin@mail.com", "Pro"), ("linkedin", "linkedin.com/in/alexrobin", "")],
        "experiences": [
            {"annee": "2022", "titre": "Molière aujourd'hui", "description": "Metteur en scène", "role": "Metteur en scène", "type_experience": "théâtre"},
        ],
    },
    {
        "nom": "Henry",
        "prenom": "Manon",
        "date_naissance": date(1997, 8, 8),
        "description": "Chanteuse pop, guitariste.",
        "taille": "164",
        "poids": "51",
        "permis": "",
        "localisations": ["Marseille"],
        "langues": [("Français", "bilingue"), ("Anglais", "courant")],
        "competences": [("Chant", "professionnel", "chant"), ("Guitare", "avancé", "musique")],
        "attributs": [("Cheveux", "Châtain"), ("Yeux", "Verts")],
        "contacts": [("email", "manon.henry@mail.com", "Pro"), ("instagram", "@manonpop", "")],
        "experiences": [
            {"annee": "2021", "titre": "Concert Zénith", "description": "Chanteuse principale", "role": "Chanteuse", "type_experience": "musique"},
        ],
    },
    {
        "nom": "Morin",
        "prenom": "Baptiste",
        "date_naissance": date(1986, 11, 25),
        "description": "Acteur, voix-off, animateur radio.",
        "taille": "180",
        "poids": "78",
        "permis": "B",
        "localisations": ["Toulouse"],
        "langues": [("Français", "natif"), ("Espagnol", "courant")],
        "competences": [("Animation", "professionnel", "radio"), ("Voix-off", "avancé", "voix")],
        "attributs": [("Cheveux", "Noirs"), ("Yeux", "Noisette")],
        "contacts": [("email", "baptiste.morin@mail.com", "Pro"), ("twitter", "@baptiste.radio", "")],
        "experiences": [
            {"annee": "2023", "titre": "Radio Sud", "description": "Animateur matinal", "role": "Animateur", "type_experience": "radio"},
        ],
    },
    {
        "nom": "Gauthier",
        "prenom": "Chloé",
        "date_naissance": date(1999, 3, 19),
        "description": "Danseuse hip-hop, chorégraphe.",
        "taille": "169",
        "poids": "54",
        "permis": "",
        "localisations": ["Bordeaux"],
        "langues": [("Français", "bilingue"), ("Anglais", "notions")],
        "competences": [("Danse hip-hop", "professionnel", "danse"), ("Chorégraphie", "avancé", "danse")],
        "attributs": [("Cheveux", "Bruns"), ("Yeux", "Marron")],
        "contacts": [("email", "chloe.gauthier@mail.com", "Pro"), ("instagram", "@chloedanse", "")],
        "experiences": [
            {"annee": "2022", "titre": "Battle National", "description": "Finaliste", "role": "Danseuse", "type_experience": "danse"},
        ],
    },
    {
        "nom": "Leclerc",
        "prenom": "Olivier",
        "date_naissance": date(1984, 12, 2),
        "description": "Acteur, scénariste, réalisateur.",
        "taille": "185",
        "poids": "82",
        "permis": "B",
        "localisations": ["Paris"],
        "langues": [("Français", "bilingue"), ("Anglais", "courant")],
        "competences": [("Scénario", "professionnel", "cinéma"), ("Réalisation", "avancé", "cinéma")],
        "attributs": [("Cheveux", "Châtain foncé"), ("Yeux", "Verts")],
        "contacts": [("email", "olivier.leclerc@mail.com", "Pro"), ("linkedin", "linkedin.com/in/oleclerc", "")],
        "experiences": [
            {"annee": "2023", "titre": "Film 'Lumière d'été'", "description": "Scénariste, réalisateur", "role": "Réalisateur", "type_experience": "cinéma"},
        ],
    },
    {
        "nom": "Barbier",
        "prenom": "Eva",
        "date_naissance": date(1996, 7, 7),
        "description": "Comédienne, chanteuse, modèle.",
        "taille": "171",
        "poids": "55",
        "permis": "B",
        "localisations": ["Lille"],
        "langues": [("Français", "bilingue"), ("Allemand", "courant")],
        "competences": [("Chant", "professionnel", "chant"), ("Mannequinat", "avancé", "mode")],
        "attributs": [("Cheveux", "Blonds"), ("Yeux", "Bleus")],
        "contacts": [("email", "eva.barbier@mail.com", "Pro"), ("instagram", "@evamodel", "")],
        "experiences": [
            {"annee": "2021", "titre": "Shooting Vogue", "description": "Modèle", "role": "Modèle", "type_experience": "mode"},
        ],
    },
]
