# Generated by Django 5.2.3 on 2025-07-02 23:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('agence', models.CharField(blank=True, max_length=255)),
                ('site_web', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('categorie', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contact', models.CharField(choices=[('email', 'Email'), ('telephone', 'Téléphone'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('autre', 'Autre')], max_length=20)),
                ('valeur', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='talent.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(blank=True, max_length=150)),
                ('sexe', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme'), ('autre', 'Autre')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='talents/photos/')),
                ('taille', models.CharField(blank=True, max_length=20)),
                ('poids', models.CharField(blank=True, max_length=20)),
                ('permis', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talents', to='talent.agent')),
                ('categories', models.ManyToManyField(blank=True, related_name='talents', to='talent.categorietalent')),
                ('langues', models.ManyToManyField(blank=True, to='talent.langue')),
                ('localisations', models.ManyToManyField(blank=True, to='talent.localisation')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talents/galerie/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie_photos', to='talent.talent')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Vidéo')], max_length=10)),
                ('fichier', models.FileField(upload_to='talents/media/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='talent.talent')),
            ],
        ),
        migrations.CreateModel(
            name='TalentCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.competence')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talent.talent')),
            ],
            options={
                'unique_together': {('talent', 'competence')},
            },
        ),
        migrations.AddField(
            model_name='talent',
            name='competences',
            field=models.ManyToManyField(blank=True, through='talent.TalentCompetence', to='talent.competence'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(blank=True, max_length=20)),
                ('titre', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='talent.talent')),
                ('type_experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talent.typeexperience')),
            ],
        ),
        migrations.CreateModel(
            name='TalentAttribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100)),
                ('valeur', models.TextField(blank=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributs', to='talent.talent')),
            ],
            options={
                'unique_together': {('talent', 'cle')},
            },
        ),
    ]
