# Generated by Django 5.2.3 on 2025-07-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
