# Generated by Django 5.2.3 on 2025-07-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_alter_talent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='prenom',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
